"""add cv fields

Revision ID: 106acff0cae3
Revises: f081089efc4f
Create Date: 2026-05-15 13:51:00.697308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '106acff0cae3'
down_revision: Union[str, None] = 'f081089efc4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('cv_url', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('cv_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'cv_text')
    op.drop_column('candidates', 'cv_url')
    # ### end Alembic commands ###
