"""add_cv_fields_to_profiles

Revision ID: 58617e98eadf
Revises: a6d74652a7f5
Create Date: 2026-05-16 03:33:24.915904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58617e98eadf'
down_revision: Union[str, None] = 'a6d74652a7f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
