"""add cv profile fields

Revision ID: a6d74652a7f5
Revises: 106acff0cae3
Create Date: 2026-05-15 14:07:15.153651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6d74652a7f5'
down_revision: Union[str, None] = '106acff0cae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('cv_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('profiles', sa.Column('cv_experience', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('profiles', sa.Column('cv_education', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('profiles', sa.Column('raw_cv_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'raw_cv_text')
    op.drop_column('profiles', 'cv_education')
    op.drop_column('profiles', 'cv_experience')
    op.drop_column('profiles', 'cv_skills')
    # ### end Alembic commands ###
